### ISSUE TITLE
vertx_stop does not appear to block

### ISSUE THREAD

**Issue by sigil66** [vert-x3/vertx-lang-ruby#16]
When running a ruby script as a verticle it would appear that vertx_stop does not block. I am not sure if this is the intent.

I have gotten around the issue utilize the vertx_stop_async method and completing the future after the async block completes.

Clarification here would be helpful.

**Comment by purplefox** [comment]
Hi, can you elaborate on what you mean by "does not block"?

**Comment by sigil66** [comment]
Sure, if I utilize async methods on objects such as an httpclient, vertx_stop executes but none of the async methods do. No error is printed. So while this may be correct given the lifecycle (has the event loop been stopped?) it wasn't obvious to me that there was an issue until digging into it.

**Comment by purplefox** [comment]
Perhaps you could illustrate what you mean with an example? I'm still not clear what you mean here.

**Comment by sigil66** [comment]
```
def vertx_stop
  puts "vertx_stop called" #prints to console
end
```

**Comment by pmlopes** [comment]
That happens due to the synchronicity of the code. Look at the flow:

1. vertx_stop is called
2. a http async client is created and a request is made adding a new callback handler to the event loop
3. vertx_stop completes (which implies, killing the event loop)

As you can see, your callback handler will not be called since the event loop is already dead.

In order to have it called you need to wait, probably using the method variant with a future.

**Comment by sigil66** [comment]
Great, thank you for the help!
